// Generated by Selenium IDE
package es.unican.ps.ucpark.presentationLayer;

import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Keys;

import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;

public class NuevoEstacionamientoTest {
  private WebDriver driver;
  JavascriptExecutor js;
  
  @Before
  public void setUp() {
	System.setProperty("webdriver.chrome.driver", "C:\\Users\\mario\\Documents"
				+"\\chromedriver_win32\\chromedriver.exe");
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
  }
  
  @After
  public void tearDown() {
    driver.quit();
  }
  
  @Test
  public void nuevoEstacionamientoTest() {
    driver.get("http://localhost:8080/UCParkWeb/");
    driver.manage().window().setSize(new Dimension(1552, 832));
    driver.findElement(By.cssSelector("h1")).click();
    driver.findElement(By.id("loginForm:email")).click();
    driver.findElement(By.id("loginForm:email")).sendKeys(Keys.CONTROL + "a");
    driver.findElement(By.id("loginForm:email")).sendKeys(Keys.DELETE);
    driver.findElement(By.id("loginForm:email")).sendKeys("mmp819@email.com");
    driver.findElement(By.id("loginForm:contrasenha")).click();
    driver.findElement(By.id("loginForm:contrasenha")).sendKeys(Keys.CONTROL + "a");
    driver.findElement(By.id("loginForm:contrasenha")).sendKeys(Keys.DELETE);
    driver.findElement(By.id("loginForm:contrasenha")).sendKeys("1234");
    driver.findElement(By.name("loginForm:j_idt11")).click();
    driver.findElement(By.name("j_idt6:j_idt12")).click();
    driver.findElement(By.cssSelector("h1")).click();
    assertThat(driver.findElement(By.cssSelector("h1")).getText(), is("Crear un nuevo estacionamiento"));
    driver.findElement(By.cssSelector("tr:nth-child(1)")).click();
    assertThat(driver.findElement(By.cssSelector("tr:nth-child(1) label")).getText(), is("Vehiculo:"));
    driver.findElement(By.cssSelector("table")).click();
    assertThat(driver.findElement(By.cssSelector("tr:nth-child(2) label")).getText(), is("Minutos:"));
    driver.findElement(By.name("nuevoEstacionamientoForm:j_idt9")).click();
    driver.findElement(By.id("nuevoEstacionamientoForm:minutos")).click();
    driver.findElement(By.cssSelector("div:nth-child(4)")).click();
    driver.findElement(By.name("nuevoEstacionamientoForm:j_idt13")).click();
    driver.findElement(By.cssSelector("html")).click();
    assertThat(driver.findElement(By.cssSelector("div:nth-child(5) td")).getText(), is("nuevoEstacionamientoForm:minutos: Error de validaci\u00f3n: el atributo especificado no est\u00e1 entre los valores esperados: 1 y 120."));
    driver.findElement(By.cssSelector("tr:nth-child(2)")).click();
    driver.findElement(By.id("nuevoEstacionamientoForm:minutos")).sendKeys(Keys.CONTROL + "a");
    driver.findElement(By.id("nuevoEstacionamientoForm:minutos")).sendKeys(Keys.DELETE);
    driver.findElement(By.id("nuevoEstacionamientoForm:minutos")).sendKeys("121");
    driver.findElement(By.cssSelector("#nuevoEstacionamientoForm > div")).click();
    driver.findElement(By.name("nuevoEstacionamientoForm:j_idt13")).click();
    driver.findElement(By.cssSelector("div:nth-child(5)")).click();
    assertThat(driver.findElement(By.cssSelector("div:nth-child(5) td")).getText(), is("nuevoEstacionamientoForm:minutos: Error de validaci\u00f3n: el atributo especificado no est\u00e1 entre los valores esperados: 1 y 120."));
    driver.findElement(By.cssSelector("tr:nth-child(2)")).click();
    driver.findElement(By.id("nuevoEstacionamientoForm:minutos")).sendKeys(Keys.CONTROL + "a");
    driver.findElement(By.id("nuevoEstacionamientoForm:minutos")).sendKeys(Keys.DELETE);
    driver.findElement(By.id("nuevoEstacionamientoForm:minutos")).sendKeys("60");
    driver.findElement(By.cssSelector("#nuevoEstacionamientoForm > div")).click();
    driver.findElement(By.name("nuevoEstacionamientoForm:j_idt13")).click();
    LocalDateTime horaActual = LocalDateTime.now().plusMinutes(60);
    DateTimeFormatter formatter = DateTimeFormatter.ofPattern("HH:mm:ss");
    String horaStr = formatter.format(horaActual);
    driver.findElement(By.cssSelector("h1")).click();
    assertThat(driver.findElement(By.cssSelector("h1")).getText(), is("Nuevo estacionamiento creado"));
    driver.findElement(By.cssSelector("tr:nth-child(1) > td:nth-child(1)")).click();
    assertThat(driver.findElement(By.cssSelector("tr:nth-child(1) label")).getText(), is("Vehiculo:"));
    driver.findElement(By.cssSelector("tr:nth-child(2) > td:nth-child(1)")).click();
    assertThat(driver.findElement(By.cssSelector("tr:nth-child(2) label")).getText(), is("Finaliza a las:"));
    driver.findElement(By.cssSelector("tr:nth-child(1) > td:nth-child(2)")).click();
    assertThat(driver.findElement(By.cssSelector("tr:nth-child(1) > td:nth-child(2)")).getText(), is("1234-ABC"));
    driver.findElement(By.cssSelector("tr:nth-child(2) > td:nth-child(2)")).click();
    assertThat(driver.findElement(By.cssSelector("tr:nth-child(2) > td:nth-child(2)")).getText(), is(horaStr));
    driver.findElement(By.name("j_idt6:j_idt14")).click();
    driver.findElement(By.name("j_idt6:j_idt12")).click();
    driver.findElement(By.name("nuevoEstacionamientoForm:j_idt9")).click();
    driver.findElement(By.id("nuevoEstacionamientoForm:minutos")).click();
    driver.findElement(By.name("nuevoEstacionamientoForm:j_idt13")).click();
    driver.findElement(By.cssSelector("div:nth-child(5) > table")).click();
    driver.findElement(By.cssSelector("div:nth-child(5) td")).click();
    driver.findElement(By.cssSelector("div:nth-child(5)")).click();
    assertThat(driver.findElement(By.cssSelector("div:nth-child(5) td")).getText(), is("El vehiculo ya tiene un estacionamiento en vigor."));
  }
}
