name: UCPark-mvn

on:
    push:
        branches:
            - master
            - develop
jobs:
      build:
        runs-on: ubuntu-latest
      
        steps:
         -uses: actions/checkout@v2
         -name: Set up JDK 11
         -uses: actions/setup-java@v2
         -with:
            java-version: '11'
            distribuiton: 'adopt'
         -name: Build with Maven
         -run: mvn clean package

        
